GET http://localhost:3333/

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "user": "bdc",
    "pass": "12546463"
}

###

GET http://localhost:3333/cliente
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjIxOTQ4OTg2LCJleHAiOjE2MjE5NDkyODZ9.azNyADmlhBp_uJpJW2wsyctFlWl7a3Vjw-2Agf-zJos